const state={catalogs:[],parts:[],hotspots:[],images:[],current:null,scale:1,x:0,y:0};
const $=id=>document.getElementById(id);
Promise.all(['catalogs','parts','hotspots','images'].map(x=>fetch('data/'+x+'.json').then(r=>r.json()))).then(([c,p,h,i])=>{state.catalogs=c;state.parts=p;state.hotspots=h;state.images=i;renderCatalogs(c);$('count').textContent=c.length;if(location.hash)openCatalog(decodeURIComponent(location.hash.slice(1)));});
function renderCatalogs(list){const q=$('filter').value.toLowerCase();$('catalogs').innerHTML=list.filter(c=>(c.id+' '+c.title).toLowerCase().includes(q)).map(c=>`<div class="cat ${state.current?.id===c.id?'active':''}" data-id="${esc(c.id)}"><b>${esc(c.title||c.id)}</b><small>${esc(c.id)} · ${c.rows} rows</small></div>`).join('');document.querySelectorAll('.cat').forEach(e=>e.onclick=()=>openCatalog(e.dataset.id));}
function openCatalog(id){const c=state.catalogs.find(x=>x.id===id);if(!c)return;state.current=c;location.hash=encodeURIComponent(id);$('title').textContent=(c.title||c.id)+' — '+c.id;renderCatalogs(state.catalogs);let img=c.image||null;if(!img){$('diagram').style.display='none';$('empty').style.display='block';}else{$('empty').style.display='none';const im=$('diagram');im.onload=()=>fit();im.src='images/'+encodeURIComponent(img);im.style.display='block';}renderParts();renderHotspots();}
function renderParts(){const arr=state.parts.filter(p=>p.catalog===state.current.id);$('partCount').textContent=arr.length;$('rows').innerHTML=arr.map(p=>`<tr><td>${esc(p.position)}</td><td><a href="#" data-id="${esc(p.id)}">${esc(p.partNumber)}</a></td><td>${esc(p.description)}</td><td>${esc(p.quantity)}</td></tr>`).join('');document.querySelectorAll('#rows a').forEach(a=>a.onclick=e=>{e.preventDefault();showPart(a.dataset.id)});}
function renderHotspots(){const box=$('hotspots');box.innerHTML='';if(!state.current?.image)return;const im=state.current.image;const meta=state.images.find(x=>x.file===im);if(!meta)return;state.hotspots.filter(h=>h.image===im).forEach(h=>{const d=document.createElement('div');d.className='hot';d.title=h.position;d.style.left=(h.left/meta.width*100)+'%';d.style.top=(h.top/meta.height*100)+'%';d.style.width=((h.right-h.left)/meta.width*100)+'%';d.style.height=((h.bottom-h.top)/meta.height*100)+'%';d.onclick=()=>{const p=state.parts.find(x=>x.catalog===state.current.id&&x.position===h.position);if(p)showPart(p.id);};box.appendChild(d);});}
function showPart(id){const p=state.parts.find(x=>x.id===id);if(!p)return;$('mpos').textContent='Position '+(p.position||'');$('mpart').textContent='Part Number: '+p.partNumber;$('mdesc').textContent=p.description||'No description';$('mqty').textContent='Quantity: '+(p.quantity||'');$('copy').onclick=()=>navigator.clipboard?.writeText(p.partNumber);$('modal').classList.add('show');}
function fit(){const im=$('diagram'),box=$('canvas');if(!im.naturalWidth)return;const s=Math.min((box.clientWidth-20)/im.naturalWidth,(box.clientHeight-20)/im.naturalHeight);state.scale=Math.min(s,1);state.x=(box.clientWidth-im.naturalWidth*state.scale)/2;state.y=(box.clientHeight-im.naturalHeight*state.scale)/2;apply();}
function apply(){const im=$('diagram');im.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.scale})`;const hs=$('hotspots');hs.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.scale})`;hs.style.transformOrigin='0 0';}
$('zin').onclick=()=>{state.scale*=1.25;apply()};$('zout').onclick=()=>{state.scale/=1.25;apply()};$('fit').onclick=fit;$('reset').onclick=fit;$('filter').oninput=()=>renderCatalogs(state.catalogs);$('search').oninput=e=>{const q=e.target.value.toLowerCase();if(!q)return renderCatalogs(state.catalogs);const ps=state.parts.filter(p=>(p.partNumber+' '+p.description+' '+p.position+' '+p.catalog).toLowerCase().includes(q));const ids=[...new Set(ps.map(p=>p.catalog))];renderCatalogs(state.catalogs.filter(c=>ids.includes(c.id)));};$('theme').onclick=()=>document.body.classList.toggle('dark');$('close').onclick=()=>$('modal').classList.remove('show');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.remove('show')};window.onresize=()=>{if(state.current)fit()};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
