const $=s=>document.querySelector(s);let catalogs=[],parts=[],hotspots=[],images=[],active=null,scale=1;let byImg={},byCat={};
Promise.all(['catalogs','parts','hotspots','images'].map(x=>fetch(`data/${x}.json`).then(r=>r.json()))).then(([c,p,h,i])=>{catalogs=c;parts=p;hotspots=h;images=i;images.forEach(x=>byImg[x.image]=x);parts.forEach(x=>(byCat[x.catalog]??=[]).push(x));renderCats();});
function renderCats(){let q=$('#catfilter').value.toLowerCase();$('#cats').innerHTML=catalogs.filter(c=>(c.id+' '+c.title).toLowerCase().includes(q)).map(c=>`<div class="cat ${active===c.id?'active':''}" onclick="openCat('${esc(c.id)}')"><b>${esc(c.id)}</b><small>${esc(c.title||'')}</small></div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function openCat(id){active=id;renderCats();let im=byImg[id];$('#crumb').textContent=(id+' — '+(catalogs.find(c=>c.id===id)?.title||''));let cv=$('#canvas'),ctx=cv.getContext('2d');$('#empty').style.display='none';$('#hotspots').innerHTML='';if(!im){cv.width=800;cv.height=500;ctx.clearRect(0,0,800,500);ctx.fillStyle='#888';ctx.fillText('No diagram for this assembly',30,40);return}let resp=await fetch('images/'+im.image);let buf=await resp.arrayBuffer();try{let t=new Tiff({buffer:buf});let c=t.toCanvas();cv.width=c.width;cv.height=c.height;ctx.drawImage(c,0,0);$('#hotspots').style.width=cv.width+'px';$('#hotspots').style.height=cv.height+'px';scale=1;fit();drawHotspots(im.image,cv.width,cv.height)}catch(e){ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#f66';ctx.fillText('Diagram could not be decoded: '+e,20,30)}renderResults(byCat[id]||[])}
function drawHotspots(img,w,h){let hs=hotspots.filter(x=>x.image===img);let layer=$('#hotspots');hs.forEach(x=>{let d=document.createElement('div');d.className='hs';d.style.left=(x.left/w*100)+'%';d.style.top=(x.top/h*100)+'%';d.style.width=((x.right-x.left)/w*100)+'%';d.style.height=((x.bottom-x.top)/h*100)+'%';d.title=`Pos ${x.position} ${x.part_number}`;d.onclick=()=>{let p=parts.find(y=>y.id===x.part_id);if(p) alert(`${p.part_number}\n${p.description}\nQty: ${p.qty}\nPosition: ${p.position}`)};layer.appendChild(d)})}
function renderResults(list){$('#count').textContent=list.length+' parts';$('#results').innerHTML=list.slice(0,500).map(p=>`<div class="row" onclick="alert('${esc(p.part_number)}\\n${esc(p.description)}\\nQty: ${esc(p.qty)}\\nPosition: ${esc(p.position)}')"><div class="pos">${esc(p.position)}</div><div><b>${esc(p.part_number)}</b><br><span>${esc(p.description)}</span></div><div>${esc(p.qty)}</div><div>${esc(p.type)}</div></div>`).join('')}
function fit(){let v=$('#viewer'),cv=$('#canvas');let sx=(v.clientWidth-20)/cv.width,sy=(v.clientHeight-20)/cv.height;scale=Math.max(.05,Math.min(sx,sy));cv.style.transform=`scale(${scale})`;$('#hotspots').style.transform=`scale(${scale})`;$('#hotspots').style.transformOrigin='top left';}
$('#catfilter').oninput=renderCats;$('#search').oninput=()=>{let q=$('#search').value.toLowerCase();let list=parts.filter(p=>(p.part_number+' '+p.description+' '+p.position+' '+p.catalog).toLowerCase().includes(q)).slice(0,500);renderResults(list);if(list[0]) openCat(list[0].catalog)};$('#fit').onclick=fit;$('#zin').onclick=()=>zoom(1.2);$('#zout').onclick=()=>zoom(.8);function zoom(f){scale*=f;$('#canvas').style.transform=`scale(${scale})`;$('#hotspots').style.transform=`scale(${scale})`;$('#hotspots').style.transformOrigin='top left'}$('#theme').onclick=()=>document.body.classList.toggle('dark');
